## TensorFlow

TensorFlow is an open source software library for numerical computation using data flow graphs
(data fow graphs를 이용하여 numerical 계산을 하는 library)

using python!

### What is a Data Flow Graph?

Nodes in the graph represent mathematical operations

Edges represent the multidimensional data arrays(tensors) communicated between them (Edge = Data)

In [8]:
import numpy as np

#delimiter는 ',' 로 구분지을 것이라는 뜻
xy = np.loadtxt('data-01-test-score.csv', delimiter =',', dtype = np.float32)

x_data = xy[:, 0:-1]
#target data 인 y_data는 마지막 열
y_data = xy[:,[-1]]

#makeing sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [9]:
import tensorflow as tf

tf.__version__

'2.6.0'

In [10]:
#Create a constant op
#This op is added as a node to the defaullt graph

hello = tf.constant('hello, TensorFlow!')

tf.print(hello)

hello, TensorFlow!


### TensorFlow Mechanics 

1. Build graph using TensorFlow operations

2. tf.print ( no run needed now )

3. update variables in the graph (and return values)

### Computational Graph

In [19]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0, tf.float32)
node3 = tf.add(node1,node2)

In [20]:
print('node1:' , node1, 'node2:', node2)
print('node3', node3)

node1: tf.Tensor(3.0, shape=(), dtype=float32) node2: tf.Tensor(4.0, shape=(), dtype=float32)
node3 tf.Tensor(7.0, shape=(), dtype=float32)


In [32]:
tf.print('(node1, node2): ', ([node1,node2]))
tf.print('(node3) : %d' %node3)

(node1, node2):  [3, 4]
(node3) : 7


### @tf.fuction 

In [34]:
@tf.function
def adder(a,b):
    return a+b

A = tf.constant(1)
B = tf.constant(2)

tf.print(adder(A,B))

3


### Everything is Tensor (Tensors are arrays)

In [35]:
3 # a rank 0 tensor; this is a scaer with shape []

[1.,2.,3.] # a rank 1 tensor; this is a vector with shape [3]
[[1.,2.,3.], [4.,5.,6.]] # a rank 2 tensor; a matrix with shape [2,3]
[[[1.,2.,3.]], [[7.,8.,9.]]] # a rank 3 tensor with shape [2,1,3]

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

#### Tensor Ranks, Shapes, and Types

1차원 rank = 1, 2차원, rank = 2 

Shape : element들이 몇개씩 들어있는지

Types : float32 is usual