In [1]:
# Lab 12 Character Sequence RNN
import tensorflow as tf
import numpy as np

In [2]:
sample = 'if you want you'
idx2char = list(set(sample)) # index -> char
char2idx = {c : i for i,c in enumerate(idx2char)} #char -> index

In [3]:
print(idx2char)
print(char2idx)
print(char2idx['a'])

['a', 'o', 'y', 'u', 't', 'w', 'n', 'f', 'i', ' ']
{'a': 0, 'o': 1, 'y': 2, 'u': 3, 't': 4, 'w': 5, 'n': 6, 'f': 7, 'i': 8, ' ': 9}
0


In [20]:
#hyper parameters

dic_size = len(char2idx) #RNN input size(one hot size)
hidden_size = len(char2idx) # RNN output size
num_classes = len(char2idx) # final output size (RNN or softmax, etc)
batch_size = 1 # one sample data, one batch
sequence_length = len(sample) # number of lstm rollings (unit #)
learning_rate = 0.1

15


In [5]:
sample_idx = [char2idx[c] for c in sample] #char to index
x_data = [sample_idx[:-1]] # X data sample (0~n-1) : hello : hell
y_data = [sample_idx[1:]] # Y label sample (1 ~ n) hello: ello

In [6]:
print(sample_idx) #if you want you 의 index
print(x_data)
print(y_data)

[8, 7, 9, 2, 1, 3, 9, 5, 0, 6, 4, 9, 2, 1, 3]
[[8, 7, 9, 2, 1, 3, 9, 5, 0, 6, 4, 9, 2, 1]]
[[7, 9, 2, 1, 3, 9, 5, 0, 6, 4, 9, 2, 1, 3]]


In [7]:
x_one_hot_eager = tf.one_hot(x_data, num_classes)
x_one_hot_numpy = tf.keras.utils.to_categorical(x_data,num_classes)
y_one_hot_eager = tf.one_hot(y_data, num_classes)

In [19]:
print(x_one_hot_eager.shape)
print(x_one_hot_eager)

(1, 14, 10)
tf.Tensor(
[[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]], shape=(1, 14, 10), dtype=float32)


In [9]:
print(x_one_hot_numpy) # if you want yo

[[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [10]:
print(y_one_hot_eager) # f you want you

tf.Tensor(
[[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]], shape=(1, 14, 10), dtype=float32)


In [11]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.LSTM(units = num_classes, 
                input_shape = (sequence_length, x_one_hot_eager.shape[2]),
                                  return_sequences = True                                 
                                 ))

In [12]:
tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=num_classes, activation='softmax')))

In [13]:
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 15, 10)            840       
_________________________________________________________________
time_distributed (TimeDistri (None, 15, 10)            110       
Total params: 950
Trainable params: 950
Non-trainable params: 0
_________________________________________________________________


In [14]:
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate),
                 metrics=['accuracy'])

C:\Users\queenSSH\anaconda3\envs\sshstudy\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [15]:
tf.model.fit(x_one_hot_eager, y_one_hot_eager, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 1s/step - loss: 2.3063 - accuracy: 0.1429
Epoch 2/50
1/1 [==============================] - 0s 5ms/step - loss: 2.1437 - accuracy: 0.2857
Epoch 3/50
1/1 [==============================] - 0s 5ms/step - loss: 1.9432 - accuracy: 0.2857
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 1.6837 - accuracy: 0.4286
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 1.4038 - accuracy: 0.5714
Epoch 6/50
1/1 [==============================] - 0s 5ms/step - loss: 1.0952 - accuracy: 0.7857
Epoch 7/50
1/1 [==============================] - 0s 6ms/step - loss: 0.8455 - accuracy: 0.7857
Epoch 8/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6709 - accuracy: 0.9286
Epoch 9/50
1/1 [==============================] - 0s 5ms/step - loss: 0.4440 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 5ms/step - loss: 0.3314 - accuracy: 1.0000
Epoch 11/50
1/1 [=======================

In [16]:
predictions = tf.model.predict(x_one_hot_eager)

In [17]:
for i, prediction in enumerate(predictions):
    # print char using argmax, dict
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]

    print("\tPrediction str: ", ''.join(result_str))

	Prediction str:  f you want you
