In [1]:
# Lab 12 RNN
import numpy as np
import tensorflow as tf

In [2]:
idx2char = ['h', 'i', 'e', 'l', 'o']
# Teach hello: hihell -> ihello
# x_data = [[0, 1, 0, 2, 3, 3]]  # hihell
y_data = [[1, 0, 2, 3, 3, 4]]  # ihello

In [3]:
num_classes = 5
input_dim = 5  # one-hot size, same as hidden_size to directly predict one-hot
sequence_length = 6  # |ihello| == 6
learning_rate = 0.1

In [4]:
x_one_hot = np.array([[[1, 0, 0, 0, 0],    # h 0
                       [0, 1, 0, 0, 0],    # i 1
                       [1, 0, 0, 0, 0],    # h 0
                       [0, 0, 1, 0, 0],    # e 2
                       [0, 0, 0, 1, 0],    # l 3
                       [0, 0, 0, 1, 0]]],  # l 3
                     dtype=np.float32)


In [5]:
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=num_classes)
print(x_one_hot.shape)
print(y_one_hot.shape)

(1, 6, 5)
(1, 6, 5)


In [17]:
print(y_one_hot)

[[[0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]]


In [6]:
tf.model = tf.keras.Sequential()

### 1 Cell 만들기

#### Cell 의 사이즈 (units 사이즈 지정)

make cell and add it to RNN layer

input_shape = (1,6,5) => number of sequence (batch), length of sequence, size of input dim

In [8]:
cell = tf.keras.layers.LSTMCell(units = num_classes, input_shape =(sequence_length, input_dim))
                                                                    #(6,5)
tf.model.add(tf.keras.layers.RNN(cell = cell, return_sequences = True))

#### single LSTM layer can be used as well instead of creating LSTMCell
 tf.model.add(tf.keras.layers.LSTM(units=num_classes, input_shape=(sequence_length, input_dim), return_sequences=True))

In [10]:
#fully connected layer
                                                                            # 5
tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units = num_classes, activation = 'softmax')))

In [12]:
import warnings
warnings.filterwarnings('ignore')

tf.model.compile(loss = 'categorical_crossentropy', 
                 optimizer = tf.keras.optimizers.Adam(lr = learning_rate),
                                metrics = ['accuracy'])

In [13]:
tf.model.fit(x_one_hot, y_one_hot, epochs = 50)
tf.model.summary()

Epoch 1/50
1/1 [==============================] - 1s 1s/step - loss: 1.5965 - accuracy: 0.3333
Epoch 2/50
1/1 [==============================] - 0s 3ms/step - loss: 1.4871 - accuracy: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 2ms/step - loss: 1.3904 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 3ms/step - loss: 1.2840 - accuracy: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 3ms/step - loss: 1.1780 - accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 3ms/step - loss: 1.0318 - accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 3ms/step - loss: 0.8940 - accuracy: 0.5000
Epoch 8/50
1/1 [==============================] - 0s 3ms/step - loss: 0.7683 - accuracy: 0.8333
Epoch 9/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6700 - accuracy: 0.8333
Epoch 10/50
1/1 [==============================] - 0s 3ms/step - loss: 0.5865 - accuracy: 0.8333
Epoch 11/50
1/1 [=======================

In [16]:
predictions = tf.model.predict(x_one_hot)

for i, prediction in enumerate(predictions):
    print(prediction)
    
    #print char using argmax, dict
    result_str = [idx2char[c] for c in np.argmax(prediction, axis =1)]
    print(result_str)
    print('\tPrediction str:', ''.join(result_str))

[[3.02281587e-05 9.98465419e-01 1.46618008e-03 1.97481404e-05
  1.85058434e-05]
 [9.97997940e-01 6.11009455e-05 1.12724883e-04 3.39172657e-05
  1.79422775e-03]
 [4.64754179e-04 9.36275639e-04 9.97771561e-01 8.27440410e-04
  5.80957042e-08]
 [4.54871224e-05 9.87228850e-06 1.32789300e-03 9.98612285e-01
  4.34836420e-06]
 [1.00693935e-04 5.60691005e-05 1.85330209e-05 9.98747110e-01
  1.07760984e-03]
 [1.77897478e-03 5.83601332e-06 1.16674115e-09 1.22961623e-03
  9.96985614e-01]]
['i', 'h', 'e', 'l', 'l', 'o']
	Prediction str: ihello
