In [11]:
import tensorflow as tf
import numpy as np

sentence = ("if you want to build a ship, don't drum up people together to "
            "collect wood and don't assign them tasks and work, but rather "
            "teach them to long for the endless immensity of the sea.")

### 데이터 전처리

In [38]:
char_set = list(set(sentence))
char_dic = {w : i for i,w in enumerate(char_set)} # w 가 word, i 가 index

In [39]:
print(char_set)

['a', ',', "'", 'f', 'g', 'b', 'l', 'h', 'n', 'u', ' ', 'k', 'w', 'd', 'o', 'i', 'p', 'e', '.', 'm', 'c', 'r', 't', 's', 'y']


In [40]:
print(char_dic)

{'a': 0, ',': 1, "'": 2, 'f': 3, 'g': 4, 'b': 5, 'l': 6, 'h': 7, 'n': 8, 'u': 9, ' ': 10, 'k': 11, 'w': 12, 'd': 13, 'o': 14, 'i': 15, 'p': 16, 'e': 17, '.': 18, 'm': 19, 'c': 20, 'r': 21, 't': 22, 's': 23, 'y': 24}


In [13]:
data_dim = len(char_set)
hidden_size = len(char_set)
num_classes = len(char_set)
sequence_length = 10 # Any arbitrary number
learning_rate = 0.1

In [14]:
dataX =[]
dataY =[]

for i in range(0, len(sentence) - sequence_length):
    x_str = sentence[i:i+sequence_length]
    y_str = sentence[i+1:i+sequence_length+1]
    
    print(i, x_str, '->', y_str)
    
    x = [char_dic[c] for c in x_str] # x_str to index
    y = [char_dic[c] for c in y_str] # y_str to index
     
    dataX.append(x) #index 대입
    dataY.append(y)

0 if you wan -> f you want
1 f you want ->  you want 
2  you want  -> you want t
3 you want t -> ou want to
4 ou want to -> u want to 
5 u want to  ->  want to b
6  want to b -> want to bu
7 want to bu -> ant to bui
8 ant to bui -> nt to buil
9 nt to buil -> t to build
10 t to build ->  to build 
11  to build  -> to build a
12 to build a -> o build a 
13 o build a  ->  build a s
14  build a s -> build a sh
15 build a sh -> uild a shi
16 uild a shi -> ild a ship
17 ild a ship -> ld a ship,
18 ld a ship, -> d a ship, 
19 d a ship,  ->  a ship, d
20  a ship, d -> a ship, do
21 a ship, do ->  ship, don
22  ship, don -> ship, don'
23 ship, don' -> hip, don't
24 hip, don't -> ip, don't 
25 ip, don't  -> p, don't d
26 p, don't d -> , don't dr
27 , don't dr ->  don't dru
28  don't dru -> don't drum
29 don't drum -> on't drum 
30 on't drum  -> n't drum u
31 n't drum u -> 't drum up
32 't drum up -> t drum up 
33 t drum up  ->  drum up p
34  drum up p -> drum up pe
35 drum up pe -> rum up peo
36

In [21]:
print(len(dataX))
print(dataX[0])

170
[15, 3, 10, 24, 14, 9, 10, 12, 0, 8]


In [15]:
batch_size = len(dataX)

In [16]:
# One -hot Encoding

X_one_hot = tf.one_hot(dataX, num_classes)
Y_one_hot = tf.one_hot(dataY, num_classes)

In [22]:
print(X_one_hot)

tf.Tensor(
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 1.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 1. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 1. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 1. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 1. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 1. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]]

In [23]:
print(X_one_hot.shape)  # check out the shape (170, 10, 25)
print(Y_one_hot.shape)  # check out the shape

(170, 10, 25)
(170, 10, 25)


### Model 생성

In [25]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.LSTM(units = num_classes, input_shape=(sequence_length, X_one_hot.shape[2]),
                                 return_sequences = True))
tf.model.add(tf.keras.layers.LSTM(units = num_classes,return_sequences = True))
tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units = num_classes,
                                                                  activation = 'softmax')))
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 10, 25)            5100      
_________________________________________________________________
lstm_1 (LSTM)                (None, 10, 25)            5100      
_________________________________________________________________
time_distributed (TimeDistri (None, 10, 25)            650       
Total params: 10,850
Trainable params: 10,850
Non-trainable params: 0
_________________________________________________________________


In [26]:
tf.model.compile(loss = 'categorical_crossentropy', optimizer = tf.keras.optimizers.Adam(lr=learning_rate),
                metrics=['accuracy'])

C:\Users\queenSSH\anaconda3\envs\sshstudy\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [27]:
tf.model.fit(X_one_hot, Y_one_hot, epochs = 100)

Epoch 1/100
6/6 [==============================] - 2s 6ms/step - loss: 3.0662 - accuracy: 0.1041
Epoch 2/100
6/6 [==============================] - 0s 5ms/step - loss: 2.8747 - accuracy: 0.1447
Epoch 3/100
6/6 [==============================] - 0s 5ms/step - loss: 2.6376 - accuracy: 0.1953
Epoch 4/100
6/6 [==============================] - 0s 5ms/step - loss: 2.1880 - accuracy: 0.3500
Epoch 5/100
6/6 [==============================] - 0s 5ms/step - loss: 1.7332 - accuracy: 0.5035
Epoch 6/100
6/6 [==============================] - 0s 5ms/step - loss: 1.3693 - accuracy: 0.6018
Epoch 7/100
6/6 [==============================] - 0s 5ms/step - loss: 1.0710 - accuracy: 0.6888
Epoch 8/100
6/6 [==============================] - 0s 5ms/step - loss: 0.8760 - accuracy: 0.7471
Epoch 9/100
6/6 [==============================] - 0s 5ms/step - loss: 0.6824 - accuracy: 0.7906
Epoch 10/100
6/6 [==============================] - 0s 5ms/step - loss: 0.5815 - accuracy: 0.8224
Epoch 11/100
6/6 [===========

6/6 [==============================] - 0s 5ms/step - loss: 0.2546 - accuracy: 0.8835
Epoch 85/100
6/6 [==============================] - 0s 5ms/step - loss: 0.2491 - accuracy: 0.8912
Epoch 86/100
6/6 [==============================] - 0s 5ms/step - loss: 0.2528 - accuracy: 0.8859
Epoch 87/100
6/6 [==============================] - 0s 5ms/step - loss: 0.2546 - accuracy: 0.8900
Epoch 88/100
6/6 [==============================] - 0s 5ms/step - loss: 0.2508 - accuracy: 0.8906
Epoch 89/100
6/6 [==============================] - 0s 5ms/step - loss: 0.2564 - accuracy: 0.8859
Epoch 90/100
6/6 [==============================] - 0s 5ms/step - loss: 0.2492 - accuracy: 0.8871
Epoch 91/100
6/6 [==============================] - 0s 5ms/step - loss: 0.2512 - accuracy: 0.8906
Epoch 92/100
6/6 [==============================] - 0s 5ms/step - loss: 0.2476 - accuracy: 0.8900
Epoch 93/100
6/6 [==============================] - 0s 5ms/step - loss: 0.2512 - accuracy: 0.8906
Epoch 94/100
6/6 [===============

# enumerate 부분.....

In [34]:
results = tf.model.predict(X_one_hot)

for j, results in enumerate(results):
    index = np.argmax(results, axis =1)

    if j==0: #print all for the first result to make a sentenxe
        print(''.join([char_set[t] for t in index]), end ='')
    else:
        print(char_set[index[-1]], end='')

f you want to build a ship, don't drum up people together to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.

In [41]:
print(results)

[[8.18107277e-04 1.93590477e-05 1.98178113e-05 3.86856534e-02
  3.03689037e-02 8.21652720e-05 4.16884273e-02 7.17981891e-07
  3.52641076e-01 2.62452830e-02 2.28149235e-01 5.37520066e-07
  4.69716542e-06 1.54263517e-02 4.14308272e-02 1.31157985e-05
  4.02156897e-02 2.36376247e-04 2.15022988e-06 1.79732486e-03
  3.26716661e-04 1.79408401e-01 1.02666591e-03 1.33787538e-03
  5.45936382e-05]
 [9.36780780e-05 2.26090826e-12 9.74756127e-12 1.42297419e-14
  1.09061524e-08 3.20852931e-16 3.05701036e-07 6.39284845e-05
  4.67879335e-09 3.09535834e-11 9.99267638e-01 1.39417281e-07
  1.22049121e-10 1.11052202e-10 5.38181921e-04 7.42795407e-08
  2.25565673e-13 2.47268363e-05 1.95337652e-11 4.70905889e-07
  2.94862433e-11 9.39144411e-06 9.49380933e-07 5.52229512e-11
  5.34715866e-07]
 [9.09973915e-06 3.36425800e-14 4.77618889e-10 1.45521817e-08
  4.71262508e-11 6.39808776e-14 5.12212072e-13 1.03398328e-07
  2.74581367e-07 7.82925636e-04 5.75827962e-11 8.07640760e-11
  1.31918321e-09 4.76531481e-10 1.