In [1]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np

In [4]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]

#y_data는 target data 로 마지막 열에 해당한다
y_data = xy[:, [-1]]

In [5]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [6]:
tf.model = tf.keras.Sequential()

In [7]:
#activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer
tf.model.add(tf.keras.layers.Dense(units =1, input_dim=3, activation= 'linear'))
# tf.model.add(tf.keras.layers.Activation('linear'))

tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [9]:
import warnings
warnings.filterwarnings('ignore')

tf.model.compile(loss = 'mse', optimizer = tf.keras.optimizers.SGD(lr = 1e-5))
history = tf.model.fit(x_data, y_data, epochs = 200)

Epoch 1/200
1/1 [==============================] - 0s 137ms/step - loss: 14.2116
Epoch 2/200
1/1 [==============================] - 0s 969us/step - loss: 14.2062
Epoch 3/200
1/1 [==============================] - 0s 1ms/step - loss: 14.2008
Epoch 4/200
1/1 [==============================] - 0s 2ms/step - loss: 14.1954
Epoch 5/200
1/1 [==============================] - 0s 2ms/step - loss: 14.1901
Epoch 6/200
1/1 [==============================] - 0s 996us/step - loss: 14.1847
Epoch 7/200
1/1 [==============================] - 0s 998us/step - loss: 14.1793
Epoch 8/200
1/1 [==============================] - 0s 998us/step - loss: 14.1740
Epoch 9/200
1/1 [==============================] - 0s 998us/step - loss: 14.1686
Epoch 10/200
1/1 [==============================] - 0s 997us/step - loss: 14.1633
Epoch 11/200
1/1 [==============================] - 0s 2ms/step - loss: 14.1579
Epoch 12/200
1/1 [==============================] - 0s 2ms/step - loss: 14.1526
Epoch 13/200
1/1 [=================

1/1 [==============================] - 0s 2ms/step - loss: 13.2124


In [10]:
#Ask my Score
print('your score wil be', tf.model.predict([[100,70,101]]))
print('Other score will be', tf.model.predict([[60,70,110],[90,100,80]]))

your score wil be [[171.28326]]
Other score will be [[185.31644]
 [180.53885]]
